### ISSUE TITLE
Feature request: Support for metric units

### ISSUE THREAD

**Issue by snoopen** [built1n/rastercarve#1]
Currently all output is labelled as inches. If the gcode output is run on a metric machine the result will be scaled down since G1 will be assuming metric move instructions.

After a quick look at the code I believe simply changing the labels is all that would be needed. It would make most sense to have an option to optionally work in millimetres.

**Comment by built1n** [comment]
Hi @snoopen - this is actually even simpler than you suggest here. You should be able to get this to work by just adding an option to replace G20 with G21 in the preamble. I've been meaning to add a custom preamble option, and this would fit nicely into it.

**Comment by built1n** [comment]
Added in 37ee8730e6ec2e6edee5369b298b65a589d08fdc.

**Comment by snoopen** [comment]
amazing, looking forward to trying it out
