### ISSUE TITLE
option to set default preamble in gcode

### ISSUE THREAD

**Issue by IrishMoss** [built1n/rastercarve#2]
It's a minor issue, but it would be nice to be able to customize the gcode preamble.
I use linuxcnc, and it doesn't like the command combo on N1, so i have to manually edit it for every file.
Also have to add a S value to the M3, otherwise the spindle doesn't spin up
It complains about no 'program end' as well, so i have to add a M2 or M30 at the end of the file as well.

Again, it's really minor, as it just requires some file editing.  But would be a nice to be able to set some defaults for the gcode.
thanks.

**Comment by built1n** [comment]
Hi @IrishMoss. Thanks for reporting this. Custom G-code preambles/epilogues are at the top of my todo right now.

I'll look into how to best implement this with the CLI.

**Comment by IrishMoss** [comment]
wow, that was quick!  :)

**Comment by built1n** [comment]
Added in 2e0c87e565e5491e3a8a001e52acd553ca1948e1.
