### ISSUE TITLE
generated gcode always have negative Y

### ISSUE THREAD

**Issue by DanielYWoo** [built1n/rastercarve#3]
I tried the script to convert an image to gcode, it seems all the Y values are negative, is this expected?

```
N1624968 G1 F100 X34.799842 Y-21.827097 Z-0.002812
N1624969 G1 F100 X34.809081 Y-21.823270 Z-0.002812
N1624970 G1 F100 X34.818320 Y-21.819443 Z-0.002812
N1624971 G1 F100 X34.827558 Y-21.815616 Z-0.002812
N1624972 G1 F100 X34.836797 Y-21.811790 Z-0.002812
N1624973 G1 F100 X34.846036 Y-21.807963 Z-0.002812
N1624974 G1 F100 X34.855275 Y-21.804136 Z-0.002812
N1624975 G1 F100 X34.864514 Y-21.800309 Z-0.002812
N1624976 G1 F100 X34.873752 Y-21.796482 Z-0.002812
N1624977 G1 F100 X34.882991 Y-21.792655 Z-0.002812
N1624978 G1 F100 X34.892230 Y-21.788829 Z-0.002812

```

**Comment by built1n** [comment]
This is the expected behavior. See step 3 https://github.com/built1n/rastercarve#machining-process -- you are expected to zero the machine to the top left corner of your material, so that the image extends in the +X and -Y directions.

**Comment by DanielYWoo** [comment]
I am from Marlin so I thought the coord should be starting from zero for both x and y. Thanks for your help!

**Comment by DanielYWoo** [comment]
BTW, is it possible to generate gcode from bottom-left (positive X and Y) or top-right (negative X and Y) ?
I seems most CNC machines use top-right as origin so always negative X/Y when working, and most 3d printers use bottom-left origin, so always positive X/Y. The gcode generated by rastercarve is positive X and negative Y, that means it chooses top-left as origin, which is not very convenient to use with grbl or Marlin.

**Comment by built1n** [comment]
There is currently no support for alternative orientations and origins. It's not to hard to implement these features themselves, but the complexity comes from devising a good command-line interface to them. If you can come up with a good alternative, I'd be happy to review it.

**Comment by DanielYWoo** [comment]
OK, let me see what I can do with it later. Thanks.
