### ISSUE TITLE
Width/Height no larger than 100. Can this limit be raised?

### ISSUE THREAD

**Issue by kazafog** [built1n/rastercarve#4]
Hi,

Nice job on this little gem. My only issue is that I cannot select a size any bigger than 100 and seen as my CNC is setup as metric changing to metric via M21 means the carving can only be 100mm. I am probably missing something, but if not can this size limit be increased?

cheers
![100 size limit](https://user-images.githubusercontent.com/28880451/112458726-356d1080-8db1-11eb-8d91-11c437a027be.png)

**Comment by built1n** [comment]
This isn't a limitation in rastercarve, but rather rastercarve-live (the web interface). It's pretty easy to fix there, and I'll make the fix when I've got a bit.

**Comment by kazafog** [comment]
Aha, i should've tried rastercarve too.

Anyway, awesome job and thanks for the quick response.
